In [1]:
import utils
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

%matplotlib inline

In [2]:
train_loader, test_loader = utils.mnist()

In [3]:
batch_x, batch_y = next(iter(train_loader))
print(batch_x.shape, batch_y.shape)

torch.Size([50, 1, 28, 28]) torch.Size([50])


In [4]:
flatten_x = batch_x.view(-1, 784)
print(flatten_x.shape)

torch.Size([50, 784])


In [5]:
layer = nn.Linear(784, 10)
print([p.shape for p in layer.parameters()])
params = [p for p in layer.parameters()]
print(params[1])

[torch.Size([10, 784]), torch.Size([10])]
Parameter containing:
tensor([-0.0106,  0.0357,  0.0103, -0.0061,  0.0049, -0.0336,  0.0184,  0.0039,
        -0.0315,  0.0094], requires_grad=True)


In [6]:
hidden_x = layer(flatten_x)
print(hidden_x.shape, hidden_x[0][:10])

torch.Size([50, 10]) tensor([ 0.7224, -0.1681, -0.4913, -0.4722, -0.3724, -0.1657,  0.7930, -0.4014,
        -0.7505,  0.1213], grad_fn=<SliceBackward>)


In [7]:
rectified = F.relu(hidden_x)
print(hidden_x[0])
print(rectified[0])

tensor([ 0.7224, -0.1681, -0.4913, -0.4722, -0.3724, -0.1657,  0.7930, -0.4014,
        -0.7505,  0.1213], grad_fn=<SelectBackward>)
tensor([0.7224, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.7930, 0.0000, 0.0000,
        0.1213], grad_fn=<SelectBackward>)
